apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  wavefront-url: aHR0cHM6Ly93YXZlZnJvbnQuc3VyZg== 
  wavefront-api-token: ODk0ZTU0N2EtNjI0My00OGRhLThlNzgtMjAwOTBjOGUwNjUz
