---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-service
  name: api-gateway-service
  namespace: {{ .Values.namespace }}
    
spec:
  ports:
  - name: {{.Values.service.ports.name}}
    port: {{.Values.service.ports.gatewayPort}} 
    targetPort: {{.Values.service.ports.targetPort}}
  selector:
    app: api-gateway
  type: LoadBalancer

