---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-service
  name: api-gateway-service
  namespace: {{ .Values.namespace }}
    
spec:
  ports:
  {{- toYaml .Values.service.ports | nindent 2 }}
  selector:
    app: api-gateway
  type: LoadBalancer

