---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway-deploy
  name: api-gateway-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: {{.Values.repositoryprefix}}/spring-petclinic-cloud-api-gateway:latest
        name: api-gateway
        imagePullPolicy: Always
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        lifecycle:
          {{- toYaml .Values.lifecycle | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}        
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: activeProfiles

        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: wavefrontUri
        ports:
        - containerPort: 8080
      restartPolicy: Always
