---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vets-deploy
  name: vets-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - image: {{.Values.repositoryprefix}}/spring-petclinic-cloud-vets-service:latest
        name: vets-service
        imagePullPolicy: Always
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        lifecycle:
          {{- toYaml .Values.lifecycle | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: activeProfiles

        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: wavefrontUri

        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{.Release.Name}}-vets-db-mysql.{{ .Values.namespace }}.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=vets-db
        
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: dsUsername
              
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
             secretKeyRef:
               name: {{.Release.Name}}-vets-db-mysql
               key: mysql-root-password

        ports:
        - containerPort: {{.Values.containerPort}}
      restartPolicy: Always