---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visits-deploy
  name: visits-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - image: {{ .Values.repositoryprefix}}/spring-petclinic-cloud-visits-service:latest
        name: visits-service
        imagePullPolicy: Always
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}   
        lifecycle:
          {{- toYaml .Values.lifecycle | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: activeProfiles
        - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: wavefrontUri
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://{{.Release.Name}}-visits-db-mysql.{{ .Values.namespace }}.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom: 
            configMapKeyRef: 
              name: petclinic-config
              key: dsUsername
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
             secretKeyRef:
               name: {{.Release.Name}}-visits-db-mysql
               key: mysql-root-password

        ports:
        - containerPort: {{.Values.containerPort}}
      restartPolicy: Always
