# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: &ns spring-petclinic-staging  # create a variable ns that contains the  value of the namespace
replicaCount: 2
repositoryprefix: springcommunity 

vets-db-mysql:
  auth:
    database: service_instance_db
  namespaceOverride: *ns  # get the value of the namespace
  primary:
    persistence:
      size: 500Mi

visits-db-mysql:
  auth:
    database: service_instance_db
  namespaceOverride: *ns  # get the value of the namespace
  primary:
    persistence:
      size: 500Mi

customers-db-mysql:
  auth:
    database: service_instance_db   
  namespaceOverride: *ns  # get the value of the namespace
  primary:
    persistence:
      size: 500Mi

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1Gi

livenessProbe:
  httpGet:
    port: 8080
    path: /actuator/health/liveness
  initialDelaySeconds: 90
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 15

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 10"]

service:
  ports:
    name: "http"
    port: 8080
    gatewayPort: 80
    targetPort: 8080

restartPolicy : Always