# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: &ns spring-petclinic  # create a variable ns that contains the  value of the namespace
replicaCount: 1
repositoryprefix: springcommunity 

vets-db-mysql:
  auth:
    database: service_instance_db
  namespaceOverride: *ns  # get the value of the ns variable

visits-db-mysql:
  auth:
    database: service_instance_db
  namespaceOverride: *ns  # get the value of the ns variable

customers-db-mysql:
  auth:
    database: service_instance_db   
  namespaceOverride: *ns  # get the value of the ns variable


livenessProbe:
  httpGet:
    port: 8080
    path: /actuator/health/liveness
  initialDelaySeconds: 90
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 15

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 10"]

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 2000m
    memory: 1Gi

service:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080

containerPort: 8080

restartPolicy : Always