# Default values for petclinic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: &ns spring-petclinic  # create a variable ns that contains the  value of the namespace

repositoryprefix: springcommunity 

vets-db-mysql:
  auth:
    database: service_instance_db
  namespaceOverride: *ns  # use the ns variable to get the namespace value defined at the top 

visits-db-mysql:
  auth:
    database: service_instance_db
  namespaceOverride: *ns 

customers-db-mysql:
  auth:
    database: service_instance_db   
  namespaceOverride: *ns 


livenessProbe:
  httpGet:
    port: 8080
    path: /actuator/health/liveness
  initialDelaySeconds: 90
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 15

lifecycle:
  preStop:
    exec:
      command: ["sh", "-c", "sleep 10"]

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 2000m
    memory: 1Gi